language: php

php:
  - '7.2'

install: [
  "echo \"{\\\"http-basic\\\":{\\\"repo.magento.com\\\":{\\\"username\\\":\\\"${MAGENTO_USERNAME}\\\",\\\"password\\\":\\\"${MAGENTO_PASSWORD}\\\"}}}\" > auth.json",
  "composer install",
  "composer require magento/magento-coding-standard"
]

before_install:
  - composer self-update --1
  - composer --version

cache:
  directories:
    - $HOME/.composer/cache

script:
  - vendor/bin/phpcs --standard=vendor/magento/magento-coding-standard/Magento2 --ignore=vendor ./